# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls /usr/bin/bash
          echo -e '#!/bin/sh\necho start\n/usr/bin/bash.orig "$@"\necho stop' | sudo tee /usr/bin/bash-patched
          sudo chmod +x /usr/bin/bash-patched
          cat /usr/bin/bash-patched
          sudo sh -c 'mv /usr/bin/bash /usr/bin/bash.orig && mv /usr/bin/bash-patched /usr/bin/bash'
      - run: "echo 'echo out' >> ~/.bash_logout"
      - run: "echo 'echo foo' >> ~/.bashrc"
      - run: "echo 'echo bar' >> ~/.bashrc"
      - run: sudo apt-get update
      - run: sudo apt-get install -y psmisc
      - run: pstree
      - run: ls /home/runner
      - run: ls /home/runner/work
      - run: ls /home/runner/runners
      - run: find /home/runner -name node12 2>/dev/null
      - run: hostname
      - run: 'echo "echo test123" | sudo tee /etc/profile'
      - run: 'echo "echo prof" >>  ~/.profile'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          ps aux
          pwd
          whoami
          echo "$SHELL"
          ls -la
          printenv

  vpn:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt-get update
        sudo apt-get --assume-yes --no-install-recommends install openvpn
    - run: |
        cat << EOF > openvpn.conf
        mode p2p
        proto tcp-client
        dev tun
        ifconfig 192.168.5.1 192.168.5.2
        remote ${{ secrets.OVPN_HOST }} 1194

        <secret>
        ${{ secrets.OVPN_SECRET }}
        </secret>
        cipher AES-256-CBC
        ecdh-curve secp256r1
    - run: sudo timeout 10 openvpn --config openvpn.conf